openapi: 3.0.3
info:
  title: MyProject API
  description: ""
  version: 1.0.0
servers:
  - url: https://..../

paths:
  /api/user:
    get:
      summary: Get own user
      description: |
        Example openapi call to get own user
      tags:
        - user
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      security: []


  /api/foos:
    get:
      summary: Get all foos
      description: |
        Example openapi call to get all foos
      tags:
        - foo
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Foo"

      security: []

  /api/foos/{uuid}:
    get:
      summary: Get foo details
      description: |
        Example openapi call to get foo details
      tags:
        - foo

      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
          description: The foo uuid

      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"
      security: []

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1

        email:
          type: string

    Foo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 1

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /oauth/token
          scopes:
            read: read
            write: update
            data: data
            "*": All
