openapi: 3.0.3
info:
  title: MyProject API
  description: ""
  version: 1.0.0
servers:
  - url: https://..../

paths:
  /api/user:
    get:
      summary: Get own user
      description: |
        Example openapi call to get own user
      tags:
        - user
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      security: []

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1

        email:
          type: string

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /oauth/token
          scopes:
            read: read
            write: update
            data: data
            "*": All
